# Generated by Django 3.1.1 on 2020-09-17 15:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CoffeMachine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('product_type', models.CharField(choices=[('COFFEE_MACHINE_LARGE', 'COFFEE_MACHINE_LARGE'), ('COFFEE_MACHINE_SMALL', 'COFFEE_MACHINE_SMALL'), ('ESPRESSO_MACHINE', 'ESPRESSO_MACHINE')], max_length=60)),
                ('name', models.CharField(max_length=60)),
                ('water_line_compatible', models.BooleanField(default=True)),
            ],
        ),
    ]
